import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

cities = [
    'Anaheim',
    'Antioch',
    'Bakersfield',
    'Beaumont',
    'Berkeley',
    'Bridgeport',
    'Burbank',
    'Chula Vista',
    'Columbia',
    'Concord',
    'Corona',
    'Costa Mesa',
    'Downey',
    'Durham',
    'East Los Angeles',
    'Edison',
    'El Monte',
    'Escondido',
    'Fairfield',
    'Fontana',
    'Fremont',
    'Fresno',
    'Fullerton',
    'Garden Grove',
    'Glendale',
    'Hayward',
    'Huntington Beach',
    'Independence',
    'Inglewood',
    'Irvine',
    'Jackson',
    'Lafayette',
    'Lakewood',
    'Lancaster',
    'Lincoln',
    'Long Beach',
    'Los Angeles',
    'Modesto',
    'Moreno Valley',
    'Newark',
    'Norwalk',
    'Oakland',
    'Oceanside',
    'Ontario',
    'Orange',
    'Oxnard',
    'Palmdale',
    'Paradise',
    'Pasadena',
    'Pomona',
    'Rancho Cucamonga',
    'Rialto',
    'Richmond',
    'Riverside',
    'Roseville',
    'Sacramento',
    'Salinas',
    'San Bernardino',
    'San Diego',
    'San Francisco',
    'San Jose',
    'Santa Ana',
    'Santa Clara',
    'Santa Clarita',
    'Santa Rosa',
    'Simi Valley',
    'Spring Valley',
    'Stockton',
    'Sunnyvale',
    'Thornton',
    'Thousand Oaks',
    'Torrance',
    'Vallejo',
    'Visalia',
    'Washington',
    'West Covina',
    'Westminster',
    'Windsor',
]

land_temp_cities = pd.read_csv(
    #'GlobalLandTemperaturesByMajorCity.csv filepath',
    header=0,
    names=[
        'dt',
        'AverageTemperature',
        'AverageTemperatureUncertainty',
        'City',
        'Country',
        'Latitude',
        'Longitude',
    ],
    usecols=['dt', 'AverageTemperature', 'City'],
)

# select rows corresponding to california cities
cal_temps = land_temp_cities.loc[land_temp_cities['City'].isin(cities)]
# select rows from LA
la_temps = cal_temps.loc[cal_temps['City'] == 'Los Angeles']
la_temps = la_temps.drop('Los Angeles')
